In [37]:
import numpy as np
import pandas as pd

In [38]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [39]:
df.shape

(7043, 21)

In [40]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [42]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [43]:
df.isna().sum().sum()

np.int64(0)

In [44]:
df.duplicated().sum()

np.int64(0)

In [45]:
df.isin([" "]).sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [46]:
df= df.replace(" ",pd.NA)

In [47]:
df.isna().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [48]:
df[df['TotalCharges'].isna()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,<NA>,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,<NA>,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,<NA>,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,<NA>,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,<NA>,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,<NA>,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,<NA>,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,<NA>,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,<NA>,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,<NA>,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,<NA>,No

In [49]:
df[df["TotalCharges"].isnull()][["tenure", "MonthlyCharges", "TotalCharges", "Churn"]]

      tenure  MonthlyCharges TotalCharges Churn
488        0           52.55         <NA>    No
753        0           20.25         <NA>    No
936        0           80.85         <NA>    No
1082       0           25.75         <NA>    No
1340       0           56.05         <NA>    No
3331       0           19.85         <NA>    No
3826       0           25.35         <NA>    No
4380       0           20.00         <NA>    No
5218       0           19.70         <NA>    No
6670       0           73.35         <NA>    No
6754       0           61.90         <NA>    No

In [50]:
df["TotalCharges"] = df["TotalCharges"].fillna(0)

In [51]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

# Exploratory Data Analysis

In [52]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [53]:
df["Churn"].value_counts(normalize=True) * 100

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [54]:
df.groupby("Churn")["tenure"].mean()

Churn
No     37.569965
Yes    17.979133
Name: tenure, dtype: float64

In [55]:
pd.crosstab(df["Contract"], df["Churn"])

Churn             No   Yes
Contract
Month-to-month  2220  1655
One year        1307   166
Two year        1647    48

In [56]:
df.groupby("Churn")["MonthlyCharges"].mean()

Churn
No     61.265124
Yes    74.441332
Name: MonthlyCharges, dtype: float64

In [57]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [58]:
df['TotalCharges']=pd.to_numeric(df['TotalCharges'])

In [59]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [60]:
for col in df.select_dtypes(include="object").columns:
    print(col, ":", df[col].unique())

customerID : ['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' ... '4801-JZAZL' '8361-LTMKD'
 '3186-AJIEK']
gender : ['Female' 'Male']
Partner : ['Yes' 'No']
Dependents : ['No' 'Yes']
PhoneService : ['No' 'Yes']
MultipleLines : ['No phone service' 'No' 'Yes']
InternetService : ['DSL' 'Fiber optic' 'No']
OnlineSecurity : ['No' 'Yes' 'No internet service']
OnlineBackup : ['Yes' 'No' 'No internet service']
DeviceProtection : ['No' 'Yes' 'No internet service']
TechSupport : ['No' 'Yes' 'No internet service']
StreamingTV : ['No' 'Yes' 'No internet service']
StreamingMovies : ['No' 'Yes' 'No internet service']
Contract : ['Month-to-month' 'One year' 'Two year']
PaperlessBilling : ['Yes' 'No']
PaymentMethod : ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn : ['No' 'Yes']

In [61]:
df = df.drop("customerID", axis=1)

# Encoding

In [62]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [63]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y

)

In [64]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(5634, 19)
(1409, 19)
(5634,)
(1409,)

In [65]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)
X_train_encoded = encoder.fit_transform(X_train.select_dtypes(include="object"))
X_test_encoded = encoder.transform(X_test.select_dtypes(include="object"))

In [36]:
print(X_train_encoded.shape)
print(X_test_encoded.shape)

(5634, 41)
(1409, 41)

In [35]:
X_train_num = X_train.select_dtypes(include=["int64", "float64"])
X_test_num = X_test.select_dtypes(include=["int64", "float64"])

In [66]:

X_train_final = np.hstack([X_train_num, X_train_encoded])
X_test_final = np.hstack([X_test_num, X_test_encoded])

In [67]:
print(X_train_final.shape)
print(X_test_final.shape)

(5634, 45)
(1409, 45)

In [68]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [69]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train_final)
X_test_scaled = scaler.transform(X_test_final)

# models

Logistic Regression

In [70]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

In [72]:
from sklearn.metrics import accuracy_score,classification_report

accuracy = accuracy_score(y_test, y_pred)

In [79]:
print("Accuracy:", round(accuracy*100))

Accuracy: 81

In [77]:
print(classification_report(y_test, y_pred)) # من العملاء اللي فعلًا عملوا Churn، الموديل قدر يكتشف 57% منهم.

              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1035
           1       0.66      0.57      0.61       374

    accuracy                           0.81      1409
   macro avg       0.75      0.73      0.74      1409
weighted avg       0.80      0.81      0.80      1409

In [80]:

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[925 110]
 [162 212]]

KNN

In [81]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

In [84]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred_knn))

print(classification_report(y_test, y_pred_knn))

Accuracy: 0.7487579843860894
              precision    recall  f1-score   support

           0       0.83      0.83      0.83      1035
           1       0.53      0.52      0.52       374

    accuracy                           0.75      1409
   macro avg       0.68      0.68      0.68      1409
weighted avg       0.75      0.75      0.75      1409

In [85]:

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,  y_pred_knn)

print(cm)

[[861 174]
 [180 194]]

SVM

In [86]:
from sklearn.svm import SVC

svm = SVC()

svm.fit(X_train_scaled, y_train)

y_pred_svm = svm.predict(X_test_scaled)

In [87]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred_svm))

print(classification_report(y_test, y_pred_svm))

Accuracy: 0.78708303761533
              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1035
           1       0.62      0.50      0.55       374

    accuracy                           0.79      1409
   macro avg       0.73      0.69      0.71      1409
weighted avg       0.78      0.79      0.78      1409

In [88]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,  y_pred_svm)

print(cm)

[[923 112]
 [188 186]]

#cross validation

In [94]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(
    model,
    X_train_scaled,
    y_train,
    cv=cv,
    scoring="accuracy"
)

print(scores.round(3)*100)
print("Mean Accuracy:", scores.mean())

[79.9 78.3 80.2 81.7 81.1]
Mean Accuracy: 0.8022734400733805

In [96]:
recall_scores = cross_val_score(
    model,
    X_train_scaled,
    y_train,
    cv=cv,
    scoring="recall"
)

print(recall_scores.round(3)*100)
print("Mean Recall:", recall_scores.mean())

[53.5 50.2 52.8 62.5 53.5]
Mean Recall: 0.5451505016722409

In [97]:
knn_recall_scores = cross_val_score(
    knn,
    X_train_scaled,
    y_train,
    cv=cv,
    scoring="recall"
)

print(knn_recall_scores)
print("Mean Recall:", knn_recall_scores.mean())

[0.52173913 0.49832776 0.5083612  0.50501672 0.49832776]
Mean Recall: 0.5063545150501672

In [98]:
svm_recall_scores = cross_val_score(
    svm,
    X_train_scaled,
    y_train,
    cv=cv,
    scoring="recall"
)

print(svm_recall_scores)
print("Mean Recall:", svm_recall_scores.mean())

[0.47157191 0.48160535 0.49832776 0.56856187 0.48829431]
Mean Recall: 0.5016722408026756

# Class Weight

In [99]:
model_balanced = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

model_balanced.fit(X_train_scaled, y_train)

y_pred_balanced = model_balanced.predict(X_test_scaled)

In [100]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_balanced))

              precision    recall  f1-score   support

           0       0.90      0.72      0.80      1035
           1       0.51      0.79      0.62       374

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409

In [101]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,  y_pred_balanced)

print(cm)

[[748 287]
 [ 80 294]]

In [102]:
balanced_recall_scores = cross_val_score(
    model_balanced,
    X_train_scaled,
    y_train,
    cv=cv,
    scoring="recall"
)

print(balanced_recall_scores)
print("Mean Recall:", balanced_recall_scores.mean())

[0.82608696 0.7458194  0.7993311  0.85284281 0.7826087 ]
Mean Recall: 0.8013377926421406

In [103]:
y_prob = model_balanced.predict_proba(X_test_scaled)[:, 1]

print(y_prob[:10])

[0.11845828 0.85190267 0.14023333 0.66641614 0.06186609 0.80570163
 0.70001916 0.29499264 0.00893026 0.65200193]

In [104]:
from sklearn.metrics import roc_auc_score

auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC:", auc)

ROC-AUC: 0.8413366400578677

# Final Model Comparison

In [107]:
results = {
    "Logistic Regression": 0.545,
    "KNN": 0.506,
    "SVM": 0.502,
    "Balanced Logistic Regression": 0.801
}

import pandas as pd

comparison = pd.DataFrame(
    results.items(),
    columns=["Model", "Churn Recall"]
)

comparison = comparison.sort_values(
    "Churn Recall",
    ascending=False
)

print(comparison)

for name, score in models.items():
    print(name, ":", score)

                          Model  Churn Recall
3  Balanced Logistic Regression         0.801
0           Logistic Regression         0.545
1                           KNN         0.506
2                           SVM         0.502
Logistic Regression : 0.545
KNN : 0.506
SVM : 0.502
Balanced Logistic Regression : 0.801

In [108]:
from sklearn.feature_selection import SelectKBest, f_classif

selector = SelectKBest(score_func=f_classif, k=10)

X_train_selected = selector.fit_transform(X_train_scaled, y_train)
X_test_selected = selector.transform(X_test_scaled)

print(X_train_selected.shape)
print(X_test_selected.shape)

(5634, 10)
(1409, 10)

In [109]:
knn_selected = KNeighborsClassifier(n_neighbors=5)

knn_selected.fit(X_train_selected, y_train)

y_pred_knn_selected = knn_selected.predict(X_test_selected)

print(classification_report(y_test, y_pred_knn_selected))

              precision    recall  f1-score   support

           0       0.82      0.87      0.84      1035
           1       0.56      0.47      0.51       374

    accuracy                           0.76      1409
   macro avg       0.69      0.67      0.68      1409
weighted avg       0.75      0.76      0.76      1409